In [59]:
# Import the pandas library for loading, cleaning, and analyzing the dataset
import pandas as pd

# Load the raw US Wind Turbine dataset using Latin-1 encoding
file_path = r"wind_turbine_20220114.csv"

df = pd.read_csv(file_path, encoding="latin-1")

# Create a working copy so the original raw dataset remains unchanged
df = df.copy()

# Display the number of rows and columns in the dataset
print(df.shape)

# Preview the first five rows to understand the dataset structure
df.head()

(70808, 27)

,case_id,faa_ors,faa_asn,usgs_pr_id,eia_id,t_state,t_county,t_fips,p_name,p_year,...,t_rsa,t_ttlh,retrofit,retrofit_year,t_conf_atr,t_conf_loc,t_img_date,t_img_srce,xlong,ylat
0,3072661,NaN,NaN,5149.0,52161.0,CA,Kern County,6029,251 Wind,1987.0,...,NaN,NaN,0,NaN,2,3,5/8/2018,Digital Globe,-118.363762,35.077908
1,3072695,NaN,NaN,5143.0,52161.0,CA,Kern County,6029,251 Wind,1987.0,...,NaN,NaN,0,NaN,2,3,5/8/2018,Digital Globe,-118.364410,35.077435
2,3072704,NaN,NaN,5146.0,52161.0,CA,Kern County,6029,251 Wind,1987.0,...,NaN,NaN,0,NaN,2,3,5/8/2018,Digital Globe,-118.364197,35.077644
3,3063272,19-028134,2014-WTE-4084-OE,NaN,NaN,IA,Story County,19169,30 MW Iowa DG Portfolio,2017.0,...,12271.85,150.0,0,NaN,3,3,4/24/2017,Digital Globe,-93.430367,42.028233
4,3053390,19-028015,2015-WTE-6386-OE,NaN,NaN,IA,Boone County,19015,30 MW Iowa DG Portfolio,2017.0,...,12271.85,150.0,0,NaN,3,3,6/1/2017,Digital Globe,-93.700424,41.977608

In [60]:
# Display the dataset dimensions to confirm the number of rows and columns
print("Shape:", df.shape)

# Preview the first five records to inspect the data structure and values
df.head()

Shape: (70808, 27)

,case_id,faa_ors,faa_asn,usgs_pr_id,eia_id,t_state,t_county,t_fips,p_name,p_year,...,t_rsa,t_ttlh,retrofit,retrofit_year,t_conf_atr,t_conf_loc,t_img_date,t_img_srce,xlong,ylat
0,3072661,NaN,NaN,5149.0,52161.0,CA,Kern County,6029,251 Wind,1987.0,...,NaN,NaN,0,NaN,2,3,5/8/2018,Digital Globe,-118.363762,35.077908
1,3072695,NaN,NaN,5143.0,52161.0,CA,Kern County,6029,251 Wind,1987.0,...,NaN,NaN,0,NaN,2,3,5/8/2018,Digital Globe,-118.364410,35.077435
2,3072704,NaN,NaN,5146.0,52161.0,CA,Kern County,6029,251 Wind,1987.0,...,NaN,NaN,0,NaN,2,3,5/8/2018,Digital Globe,-118.364197,35.077644
3,3063272,19-028134,2014-WTE-4084-OE,NaN,NaN,IA,Story County,19169,30 MW Iowa DG Portfolio,2017.0,...,12271.85,150.0,0,NaN,3,3,4/24/2017,Digital Globe,-93.430367,42.028233
4,3053390,19-028015,2015-WTE-6386-OE,NaN,NaN,IA,Boone County,19015,30 MW Iowa DG Portfolio,2017.0,...,12271.85,150.0,0,NaN,3,3,6/1/2017,Digital Globe,-93.700424,41.977608

In [61]:
# Display all column names to review the available fields in the dataset
df.columns.tolist()

['case_id',
 'faa_ors',
 'faa_asn',
 'usgs_pr_id',
 'eia_id',
 't_state',
 't_county',
 't_fips',
 'p_name',
 'p_year',
 'p_tnum',
 'p_cap',
 't_manu',
 't_model',
 't_cap',
 't_hh',
 't_rd',
 't_rsa',
 't_ttlh',
 'retrofit',
 'retrofit_year',
 't_conf_atr',
 't_conf_loc',
 't_img_date',
 't_img_srce',
 'xlong',
 'ylat']

In [62]:
# Remove leading and trailing spaces from column names to ensure consistent field references
df.columns = df.columns.str.strip()

In [63]:
# Create a mapping dictionary to rename technical source column names
# into clearer and more descriptive names for analysis and visualization
rename_mapping = {
    "case_id": "turbine_id",
    "eia_id": "plant_id",
    "t_state": "state",
    "t_county": "county",
    "p_name": "project_name",
    "p_year": "project_year",
    "p_tnum": "project_turbine_count",
    "p_cap": "project_capacity_mw",
    "t_manu": "turbine_manufacturer",
    "t_model": "turbine_model",
    "t_cap": "turbine_capacity_kw",
    "retrofit": "is_retrofitted",
    "retrofit_year": "retrofit_year",
    "xlong": "longitude",
    "ylat": "latitude"
}

# Apply the new descriptive column names to the working dataframe
df = df.rename(columns=rename_mapping)

In [64]:
# Display a summary of the dataset, including column names, data types, non-null values, and memory usage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70808 entries, 0 to 70807
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   turbine_id             70808 non-null  int64
 1   faa_ors                65016 non-null  str
 2   faa_asn                65686 non-null  str
 3   usgs_pr_id             38263 non-null  float64
 4   plant_id               65015 non-null  float64
 5   state                  70808 non-null  str
 6   county                 70808 non-null  str
 7   t_fips                 70808 non-null  int64
 8   project_name           70808 non-null  str
 9   project_year           70195 non-null  float64
 10  project_turbine_count  70808 non-null  int64
 11  project_capacity_mw    66326 non-null  float64
 12  turbine_manufacturer   65168 non-null  str
 13  turbine_model          65031 non-null  str
 14  turbine_capacity_kw    65328 non-null  float64
 15  t_hh                   64628 non-null  float64
 16  t_rd                   64874 non-null  float64
 17  t_rsa                  64874 non-null  float64
 18  t_ttlh                 64628 non-null  float64
 19  is_retrofitted         70808 non-null  int64
 20  retrofit_year          5986 non-null   float64
 21  t_conf_atr             70808 non-null  int64
 22  t_conf_loc             70808 non-null  int64
 23  t_img_date             62492 non-null  str
 24  t_img_srce             70808 non-null  str
 25  longitude              70808 non-null  float64
 26  latitude               70808 non-null  float64
dtypes: float64(12), int64(6), str(9)
memory usage: 14.6 MB

In [65]:
# Check for completely duplicated rows in the dataset
print("Duplicate rows:", df.duplicated().sum())

# Check whether the unique turbine identifier appears more than once
print("Duplicate turbine IDs:", df["turbine_id"].duplicated().sum())

Duplicate rows: 0
Duplicate turbine IDs: 0

In [66]:
# Calculate the number and percentage of missing values in each column
missing = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percent": (df.isna().mean() * 100).round(2)
})

# Sort the results from the highest to the lowest percentage of missing values
missing.sort_values("Missing_Percent", ascending=False)

                       Missing_Count  Missing_Percent
retrofit_year                  64822            91.55
usgs_pr_id                     32545            45.96
t_img_date                      8316            11.74
t_hh                            6180             8.73
t_ttlh                          6180             8.73
t_rd                            5934             8.38
t_rsa                           5934             8.38
plant_id                        5793             8.18
faa_ors                         5792             8.18
turbine_model                   5777             8.16
turbine_manufacturer            5640             7.97
turbine_capacity_kw             5480             7.74
faa_asn                         5122             7.23
project_capacity_mw             4482             6.33
project_year                     613             0.87
state                              0             0.00
turbine_id                         0             0.00
t_fips                             0             0.00
county                             0             0.00
project_turbine_count              0             0.00
project_name                       0             0.00
t_conf_atr                         0             0.00
is_retrofitted                     0             0.00
t_conf_loc                         0             0.00
t_img_srce                         0             0.00
longitude                          0             0.00
latitude                           0             0.00

In [67]:
# Display summary statistics for the project year to check its range, distribution, and missing values
df["project_year"].describe()

count    70195.000000
mean      2011.650659
std          7.879099
min       1981.000000
25%       2008.000000
50%       2012.000000
75%       2018.000000
max       2021.000000
Name: project_year, dtype: float64

In [68]:
# Count the number of turbine records for each project year, including missing values, and sort them chronologically
df["project_year"].value_counts(dropna=False).sort_index()

project_year
1981.0      10
1982.0     930
1983.0     433
1984.0     155
1985.0     516
1986.0      79
1987.0     193
1988.0     162
1989.0     288
1990.0       1
1991.0       1
1992.0       2
1994.0      10
1995.0      21
1996.0      14
1997.0     230
1998.0     186
1999.0     618
2000.0      72
2001.0    1870
2002.0     461
2003.0    1152
2004.0     268
2005.0    1638
2006.0    1418
2007.0    3200
2008.0    5047
2009.0    5701
2010.0    2962
2011.0    3497
2012.0    6768
2013.0     600
2014.0    2506
2015.0    4301
2016.0    3798
2017.0    3058
2018.0    3136
2019.0    3588
2020.0    6592
2021.0    4713
NaN        613
Name: count, dtype: int64

In [69]:
# Display the first 20 records with missing project years to investigate whether other fields can help explain the missing values
df[df["project_year"].isna()][
    [
        "turbine_id",
        "project_name",
        "state",
        "turbine_capacity_kw",
        "is_retrofitted",
        "retrofit_year"
    ]
].head(20)

,turbine_id,project_name,state,turbine_capacity_kw,is_retrofitted,retrofit_year
2274,3087206,Bacardi Puerto Rico,PR,250.0,0,NaN
2275,3087203,Bacardi Puerto Rico,PR,250.0,0,NaN
25975,3088586,Historic Victory Garden (Wind Stream),CA,NaN,0,NaN
26070,3088585,Historic Victory Garden (Wind Stream),CA,NaN,0,NaN
29056,3001878,Kalamazoo Valley Community College,MI,NaN,0,NaN
39587,3004706,NREL - NWTC,CO,600.0,0,NaN
39589,3002673,NREL - NWTC,CO,600.0,0,NaN
39590,3002127,NREL - NWTC,CO,100.0,0,NaN
53132,3064958,Santa Fe Public Works,NM,NaN,0,NaN
62711,3098967,WTAMU,TX,60.0,0,NaN
66285,3099353,unknown Andrews County,TX,NaN,0,NaN
66286,3099427,unknown Andrews County,TX,NaN,0,NaN
66287,3099436,unknown Andrews County,TX,NaN,0,NaN
66288,3108638,unknown Andrews County,TX,NaN,0,NaN
66503,3113271,unknown Baylor County,TX,NaN,0,NaN
66567,3095463,unknown Brookings County,SD,NaN,0,NaN
66569,3095586,unknown Brookings County,SD,NaN,0,NaN
66570,3093764,unknown Brookings County,SD,NaN,0,NaN
66571,3094714,unknown Brookings County,SD,NaN,0,NaN
66572,3095138,unknown Brookings County,SD,NaN,0,NaN

In [70]:
# Display summary statistics for turbine rated capacity to identify its range, distribution, and potential outliers
df["turbine_capacity_kw"].describe()

count    65328.000000
mean      1963.534151
std        717.067912
min         50.000000
25%       1500.000000
50%       2000.000000
75%       2300.000000
max       6000.000000
Name: turbine_capacity_kw, dtype: float64

In [71]:
# Check the turbine capacity field for missing, zero, and negative values
# to identify potential data-quality issues before analysis
print("Missing capacity:", df["turbine_capacity_kw"].isna().sum())

print("Zero capacity:", (df["turbine_capacity_kw"] == 0).sum())

print("Negative capacity:", (df["turbine_capacity_kw"] < 0).sum())

Missing capacity: 5480
Zero capacity: 0
Negative capacity: 0

In [72]:
# Display the 10 turbines with the smallest rated capacities to inspect unusually low values and identify potential outliers
df.nsmallest(10, "turbine_capacity_kw")[
    [
        "turbine_id",
        "project_year",
        "turbine_capacity_kw",
        "turbine_manufacturer",
        "turbine_model"
    ]
]

,turbine_id,project_year,turbine_capacity_kw,turbine_manufacturer,turbine_model
2001,3010715,2005.0,50.0,Bergey Energy,XL50
2273,3061794,2010.0,50.0,Endurance,NaN
16512,3005174,1997.0,50.0,AOC,AOC15/50
30639,3007082,1999.0,50.0,AOC,AOC15/50
30640,3072546,1999.0,50.0,AOC,AOC15/50
30641,3072536,1999.0,50.0,AOC,AOC15/50
30642,3072540,1999.0,50.0,AOC,AOC15/50
30643,3072539,1999.0,50.0,AOC,AOC15/50
31194,3008580,2010.0,50.0,Entegrity,NaN
31195,3002530,2010.0,50.0,Endurance,NaN

In [73]:
# Check whether the turbine identifier contains any missing values
print("Missing turbine IDs:", df["turbine_id"].isna().sum())

# Check whether any turbine IDs are duplicated to verify that each turbine record is unique
print("Duplicate turbine IDs:", df["turbine_id"].duplicated().sum())

Missing turbine IDs: 0
Duplicate turbine IDs: 0

In [74]:
# Display summary statistics for the project year to check the range and distribution of year values
df["project_year"].describe()

# Count turbine records by project year, including missing values, and sort the years chronologically
df["project_year"].value_counts(dropna=False).sort_index()

project_year
1981.0      10
1982.0     930
1983.0     433
1984.0     155
1985.0     516
1986.0      79
1987.0     193
1988.0     162
1989.0     288
1990.0       1
1991.0       1
1992.0       2
1994.0      10
1995.0      21
1996.0      14
1997.0     230
1998.0     186
1999.0     618
2000.0      72
2001.0    1870
2002.0     461
2003.0    1152
2004.0     268
2005.0    1638
2006.0    1418
2007.0    3200
2008.0    5047
2009.0    5701
2010.0    2962
2011.0    3497
2012.0    6768
2013.0     600
2014.0    2506
2015.0    4301
2016.0    3798
2017.0    3058
2018.0    3136
2019.0    3588
2020.0    6592
2021.0    4713
NaN        613
Name: count, dtype: int64

In [75]:
# Display summary statistics for turbine rated capacity to understand its distribution and identify potential outliers
df["turbine_capacity_kw"].describe()

# Check for missing, zero, and negative turbine capacity values to identify potential data-quality issues
print("Missing:", df["turbine_capacity_kw"].isna().sum())
print("Zero:", (df["turbine_capacity_kw"] == 0).sum())
print("Negative:", (df["turbine_capacity_kw"] < 0).sum())

Missing: 5480
Zero: 0
Negative: 0

In [76]:
# Count turbines by retrofit status, including any missing values, to understand how many turbines have been retrofitted
df["is_retrofitted"].value_counts(dropna=False)

is_retrofitted
0    64822
1     5986
Name: count, dtype: int64

In [77]:
# Assess EIA Plant ID completeness by checking missing values, unique IDs,
# and the percentage of turbine records that can potentially be linked to the EIA dataset
print("Missing:", df["plant_id"].isna().sum())
print("Unique:", df["plant_id"].nunique())
print("Coverage %:", round(df["plant_id"].notna().mean() * 100, 2))

Missing: 5793
Unique: 1193
Coverage %: 91.82

In [78]:
# Review turbine manufacturer values, including missing records,
# to identify possible inconsistencies and understand manufacturer coverage
df["turbine_manufacturer"].value_counts(dropna=False)

# Review turbine model values, including missing records,
# to identify possible inconsistencies and understand model coverage
df["turbine_model"].value_counts(dropna=False)

turbine_model
GE1.5-77       6539
NaN            5777
V110-2.0       3979
GE2.82-127     1976
SWT-2.3-108    1964
               ...
GW136             1
WES18             1
Zond              1
U57               1
DW-52-750         1
Name: count, Length: 316, dtype: int64

In [79]:
# Remove leading and trailing spaces from manufacturer and model names
# to improve text consistency and prevent duplicate categories caused by extra whitespace
df["turbine_manufacturer"] = df["turbine_manufacturer"].str.strip()
df["turbine_model"] = df["turbine_model"].str.strip()

In [80]:
# Review project names, including missing values, to identify naming inconsistencies
# and understand how turbine records are distributed across wind projects
df["project_name"].value_counts(dropna=False)

project_name
unknown Tehachapi Wind Resource Area 1        713
Stateline Wind Project                        454
Mesa Wind Farm                                432
unknown Torrance County                       355
Mojave 16, 17 & 18 (Desertwind III PPC Tru    288
                                             ...
unknown Washington County 1                     1
unknown Watonwan County                         1
unknown Wyoming County                          1
unknown Young County                            1
unknown Young County 1                          1
Name: count, Length: 1708, dtype: int64

In [81]:
# Review the number of turbine records in each state, including missing values,
# to check geographic coverage and identify any inconsistent or unexpected state codes
df["state"].value_counts(dropna=False)

state
TX    17439
IA     6148
CA     6065
OK     4905
KS     3919
IL     3462
CO     2863
MN     2687
ND     2194
OR     2087
NM     1894
WA     1825
MI     1629
IN     1615
NE     1521
WY     1520
SD     1413
NY     1197
MO     1174
MT      803
PA      751
ID      541
OH      503
WI      451
ME      412
WV      410
AZ      269
UT      208
AK      141
HI      132
NC      105
MA       92
NH       84
MD       80
VT       73
NV       68
PR       63
RI       32
TN       18
NJ        6
CT        3
VA        2
AR        1
GU        1
DE        1
FL        1
Name: count, dtype: int64

In [82]:
# Display summary statistics for longitude and latitude to validate the geographic
# coordinate ranges before using them for mapping and spatial analysis
df[["longitude", "latitude"]].describe()

          longitude      latitude
count  70808.000000  70808.000000
mean    -100.086457     38.479503
std       11.141025      5.429730
min     -171.713074     13.389381
25%     -103.037155     34.428043
50%      -99.393761     39.052442
75%      -95.202499     42.812810
max      144.722656     66.839905

In [83]:
# Define the key columns selected for the project analysis and data-quality assessment
important_cols = [
    "turbine_id",
    "plant_id",
    "state",
    "county",
    "project_name",
    "project_year",
    "turbine_manufacturer",
    "turbine_model",
    "turbine_capacity_kw",
    "retrofit_year",
    "is_retrofitted",
    "longitude",
    "latitude"
]

# Create a data-quality report showing the data type, missing values,
# missing percentage, and number of unique values for each key column
quality_report = pd.DataFrame({
    "Data_Type": df[important_cols].dtypes.astype(str),
    "Missing_Count": df[important_cols].isna().sum(),
    "Missing_Percent": (
        df[important_cols].isna().mean() * 100
    ).round(2),
    "Unique_Values": df[important_cols].nunique()
})

# Display the final data-quality report for the selected columns
quality_report

                     Data_Type  Missing_Count  Missing_Percent  Unique_Values
turbine_id               int64              0             0.00          70808
plant_id               float64           5793             8.18           1193
state                      str              0             0.00             46
county                     str              0             0.00            564
project_name               str              0             0.00           1708
project_year           float64            613             0.87             40
turbine_manufacturer       str           5640             7.97             63
turbine_model              str           5777             8.16            315
turbine_capacity_kw    float64           5480             7.74             95
retrofit_year          float64          64822            91.55              5
is_retrofitted           int64              0             0.00              2
longitude              float64              0             0.00          65190
latitude               float64              0             0.00          61962

In [84]:
# Create a separate dataset containing only records with a valid project year
# for analyses that require turbine age or historical installation information
year_df = df[df["project_year"].notna()].copy()

In [85]:
# Create a subset containing only records with both project year and turbine capacity
# so the data can be used reliably for capacity-over-time analysis
capacity_df = df[
    df["project_year"].notna() &
    df["turbine_capacity_kw"].notna()
].copy()

In [86]:
# Create a subset containing only turbines with a Plant ID
# so these records can be linked to the EIA dataset for operator analysis
eia_df = df[
    df["plant_id"].notna()
].copy()

In [87]:
# Compare retrofit status with the availability of a retrofit year
# to verify that retrofit-year missing values are logically consistent
pd.crosstab(
    df["is_retrofitted"],
    df["retrofit_year"].notna(),
    margins=True
)

retrofit_year   False  True    All
is_retrofitted
0               64822     0  64822
1                   0  5986   5986
All             64822  5986  70808

In [88]:
# Display the updated column names to confirm that the renaming was applied successfully
df.columns.tolist()

['turbine_id',
 'faa_ors',
 'faa_asn',
 'usgs_pr_id',
 'plant_id',
 'state',
 'county',
 't_fips',
 'project_name',
 'project_year',
 'project_turbine_count',
 'project_capacity_mw',
 'turbine_manufacturer',
 'turbine_model',
 'turbine_capacity_kw',
 't_hh',
 't_rd',
 't_rsa',
 't_ttlh',
 'is_retrofitted',
 'retrofit_year',
 't_conf_atr',
 't_conf_loc',
 't_img_date',
 't_img_srce',
 'longitude',
 'latitude']

In [89]:
# Display the project year column to inspect the year values recorded for each turbine
df["project_year"]

0        1987.0
1        1987.0
2        1987.0
3        2017.0
4        2017.0
          ...
70803    2016.0
70804       NaN
70805    2011.0
70806    2016.0
70807    2016.0
Name: project_year, Length: 70808, dtype: float64

In [90]:
# Define the priority columns selected for cleaning and analysis
priority_cols = [
    "turbine_id",
    "plant_id",
    "state",
    "county",
    "project_name",
    "project_year",
    "turbine_manufacturer",
    "turbine_model",
    "turbine_capacity_kw",
    "is_retrofitted",
    "retrofit_year",
    "longitude",
    "latitude"
]

# Display information about the priority columns, including data types,
# non-null counts, and missing-value presence
df[priority_cols].info()

<class 'pandas.DataFrame'>
RangeIndex: 70808 entries, 0 to 70807
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   turbine_id            70808 non-null  int64
 1   plant_id              65015 non-null  float64
 2   state                 70808 non-null  str
 3   county                70808 non-null  str
 4   project_name          70808 non-null  str
 5   project_year          70195 non-null  float64
 6   turbine_manufacturer  65168 non-null  str
 7   turbine_model         65031 non-null  str
 8   turbine_capacity_kw   65328 non-null  float64
 9   is_retrofitted        70808 non-null  int64
 10  retrofit_year         5986 non-null   float64
 11  longitude             70808 non-null  float64
 12  latitude              70808 non-null  float64
dtypes: float64(6), int64(2), str(5)
memory usage: 7.0 MB

In [91]:
# Display summary statistics for project year to check its range and distribution
df["project_year"].describe()

# Count turbine records by project year, including missing values,
# to inspect the historical distribution
df["project_year"].value_counts(dropna=False).sort_index()

project_year
1981.0      10
1982.0     930
1983.0     433
1984.0     155
1985.0     516
1986.0      79
1987.0     193
1988.0     162
1989.0     288
1990.0       1
1991.0       1
1992.0       2
1994.0      10
1995.0      21
1996.0      14
1997.0     230
1998.0     186
1999.0     618
2000.0      72
2001.0    1870
2002.0     461
2003.0    1152
2004.0     268
2005.0    1638
2006.0    1418
2007.0    3200
2008.0    5047
2009.0    5701
2010.0    2962
2011.0    3497
2012.0    6768
2013.0     600
2014.0    2506
2015.0    4301
2016.0    3798
2017.0    3058
2018.0    3136
2019.0    3588
2020.0    6592
2021.0    4713
NaN        613
Name: count, dtype: int64

In [92]:
# Count missing project-year values to quantify records that cannot be used in age-based analysis
print("Missing project years:", df["project_year"].isna().sum())

Missing project years: 613

In [93]:
# Create a subset of turbine records with missing project years
# to investigate their other available information before deciding how to handle them
missing_year = df[df["project_year"].isna()]

# Display the first 20 records with missing project years
# to identify patterns or supporting information that may explain the missing values
missing_year[
    [
        "turbine_id",
        "plant_id",
        "project_name",
        "state",
        "county",
        "turbine_capacity_kw",
        "is_retrofitted",
        "retrofit_year"
    ]
].head(20)

,turbine_id,plant_id,project_name,state,county,turbine_capacity_kw,is_retrofitted,retrofit_year
2274,3087206,NaN,Bacardi Puerto Rico,PR,Catano Municipio,250.0,0,NaN
2275,3087203,NaN,Bacardi Puerto Rico,PR,Catano Municipio,250.0,0,NaN
25975,3088586,50532.0,Historic Victory Garden (Wind Stream),CA,Kern County,NaN,0,NaN
26070,3088585,50532.0,Historic Victory Garden (Wind Stream),CA,Kern County,NaN,0,NaN
29056,3001878,NaN,Kalamazoo Valley Community College,MI,Kalamazoo County,NaN,0,NaN
39587,3004706,NaN,NREL - NWTC,CO,Jefferson County,600.0,0,NaN
39589,3002673,NaN,NREL - NWTC,CO,Jefferson County,600.0,0,NaN
39590,3002127,NaN,NREL - NWTC,CO,Jefferson County,100.0,0,NaN
53132,3064958,NaN,Santa Fe Public Works,NM,Santa Fe County,NaN,0,NaN
62711,3098967,NaN,WTAMU,TX,Randall County,60.0,0,NaN
66285,3099353,NaN,unknown Andrews County,TX,Andrews County,NaN,0,NaN
66286,3099427,NaN,unknown Andrews County,TX,Andrews County,NaN,0,NaN
66287,3099436,NaN,unknown Andrews County,TX,Andrews County,NaN,0,NaN
66288,3108638,NaN,unknown Andrews County,TX,Andrews County,NaN,0,NaN
66503,3113271,NaN,unknown Baylor County,TX,Baylor County,NaN,0,NaN
66567,3095463,NaN,unknown Brookings County,SD,Brookings County,NaN,0,NaN
66569,3095586,NaN,unknown Brookings County,SD,Brookings County,NaN,0,NaN
66570,3093764,NaN,unknown Brookings County,SD,Brookings County,NaN,0,NaN
66571,3094714,NaN,unknown Brookings County,SD,Brookings County,NaN,0,NaN
66572,3095138,NaN,unknown Brookings County,SD,Brookings County,NaN,0,NaN

In [94]:
# Check turbine capacity for missing, zero, or negative values
# to identify records that may affect capacity-based analysis
print("Missing:", df["turbine_capacity_kw"].isna().sum())
print("Zero:", (df["turbine_capacity_kw"] == 0).sum())
print("Negative:", (df["turbine_capacity_kw"] < 0).sum())

Missing: 5480
Zero: 0
Negative: 0

In [95]:
# Display the 10 turbines with the smallest rated capacities
# to investigate unusually low values and potential outliers
df.nsmallest(10, "turbine_capacity_kw")[
    [
        "turbine_id",
        "project_year",
        "turbine_manufacturer",
        "turbine_model",
        "turbine_capacity_kw"
    ]
]

,turbine_id,project_year,turbine_manufacturer,turbine_model,turbine_capacity_kw
2001,3010715,2005.0,Bergey Energy,XL50,50.0
2273,3061794,2010.0,Endurance,NaN,50.0
16512,3005174,1997.0,AOC,AOC15/50,50.0
30639,3007082,1999.0,AOC,AOC15/50,50.0
30640,3072546,1999.0,AOC,AOC15/50,50.0
30641,3072536,1999.0,AOC,AOC15/50,50.0
30642,3072540,1999.0,AOC,AOC15/50,50.0
30643,3072539,1999.0,AOC,AOC15/50,50.0
31194,3008580,2010.0,Entegrity,NaN,50.0
31195,3002530,2010.0,Endurance,NaN,50.0

In [96]:
# Count turbines by retrofit status to understand how many turbines
# have and have not undergone a recorded retrofit
df["is_retrofitted"].value_counts(dropna=False)

is_retrofitted
0    64822
1     5986
Name: count, dtype: int64

In [97]:
# Compare retrofit status with the presence of a retrofit year
# to determine whether missing retrofit years are expected or represent a data-quality issue
pd.crosstab(
    df["is_retrofitted"],
    df["retrofit_year"].notna(),
    margins=True
)

retrofit_year   False  True    All
is_retrofitted
0               64822     0  64822
1                   0  5986   5986
All             64822  5986  70808

In [98]:
# Identify records where the retrofit year occurs before the original project year
# to detect potentially inconsistent or invalid retrofit dates
df[
    df["retrofit_year"].notna()
    & df["project_year"].notna()
    & (df["retrofit_year"] < df["project_year"])
][
    ["turbine_id", "project_year", "is_retrofitted", "retrofit_year"]
]

Empty DataFrame
Columns: [turbine_id, project_year, is_retrofitted, retrofit_year]
Index: []

In [99]:
# Assess Plant ID completeness and coverage to determine how much of the
# turbine dataset can potentially be linked to EIA plant and operator information
print("Missing plant IDs:", df["plant_id"].isna().sum())
print("Coverage %:", round(df["plant_id"].notna().mean() * 100, 2))
print("Unique plants:", df["plant_id"].nunique())

Missing plant IDs: 5793
Coverage %: 91.82
Unique plants: 1193

In [100]:
# Review manufacturer and turbine model values, including missing records,
# to identify naming inconsistencies and assess data completeness
print("Turbine Manufacturers:")
display(df["turbine_manufacturer"].value_counts(dropna=False))

print("\nTurbine Models:")
display(df["turbine_model"].value_counts(dropna=False))

Turbine Manufacturers:

turbine_manufacturer
GE Wind                                                                     29137
Vestas                                                                      16259
NaN                                                                          5640
Siemens                                                                      5035
Gamesa                                                                       3077
                                                                            ...
Changzhou Railcar Propulsion Engineering Research and Development Center        1
Wind World                                                                      1
Renewtech LLC                                                                   1
Wind Energy Solutions                                                           1
Unison                                                                          1
Name: count, Length: 64, dtype: int64

Turbine Models:

turbine_model
GE1.5-77       6539
NaN            5777
V110-2.0       3979
GE2.82-127     1976
SWT-2.3-108    1964
               ...
GW136             1
WES18             1
Zond              1
U57               1
DW-52-750         1
Name: count, Length: 316, dtype: int64

In [101]:
# Create a backup of the dataframe before applying cleaning changes
# so the original state can later be compared with the cleaned dataset
df_before_cleaning = df.copy()

# Record the dataset dimensions before cleaning
print("Rows before cleaning:", len(df))
print("Columns:", len(df.columns))

Rows before cleaning: 70808
Columns: 27

In [102]:
# Define the text columns that require formatting consistency
text_cols = [
    "state",
    "county",
    "project_name",
    "turbine_manufacturer",
    "turbine_model"
]

# Remove leading and trailing whitespace from text values
# to prevent duplicate categories caused by accidental spaces
for col in text_cols:
    df[col] = df[col].str.strip()

In [ ]:
# Convert empty text values into standard missing values (NaN)
# so missing text data is represented consistently across the dataset
import numpy as np

df[text_cols] = df[text_cols].replace(
    r"^\s*$",
    np.nan,
    regex=True
)

In [104]:
# Convert key numerical fields to numeric data types to ensure they can be
# correctly used in calculations, comparisons, and statistical analysis
numeric_cols = [
    "turbine_id",
    "plant_id",
    "project_year",
    "turbine_capacity_kw",
    "retrofit_year",
    "longitude",
    "latitude"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [105]:
# Identify turbines where the recorded retrofit year occurs before the project year
# to detect logically inconsistent retrofit dates
retrofit_before_project = df[
    df["retrofit_year"].notna()
    & df["project_year"].notna()
    & (df["retrofit_year"] < df["project_year"])
]

# Count the number of records with inconsistent retrofit dates
print(
    "Retrofit years earlier than project year:",
    len(retrofit_before_project)
)

# Display up to 20 inconsistent records for further investigation
retrofit_before_project[
    [
        "turbine_id",
        "project_name",
        "project_year",
        "is_retrofitted",
        "retrofit_year"
    ]
].head(20)

Retrofit years earlier than project year: 0

Empty DataFrame
Columns: [turbine_id, project_name, project_year, is_retrofitted, retrofit_year]
Index: []

In [106]:
# Validate latitude and longitude values to identify coordinates
# outside the valid geographic ranges before mapping the turbines
invalid_coordinates = df[
    ~df["latitude"].between(-90, 90)
    | ~df["longitude"].between(-180, 180)
]

print("Invalid coordinates:", len(invalid_coordinates))

Invalid coordinates: 0

In [107]:
# Define the priority fields used in the project's main analysis
priority_cols = [
    "turbine_id",
    "plant_id",
    "state",
    "county",
    "project_name",
    "project_year",
    "turbine_manufacturer",
    "turbine_model",
    "turbine_capacity_kw",
    "is_retrofitted",
    "retrofit_year",
    "longitude",
    "latitude"
]

# Create a final data-quality summary for the priority fields
# showing data types, missing values, missing percentages, and unique values
quality_report = pd.DataFrame({
    "data_type": df[priority_cols].dtypes.astype(str),
    "missing_count": df[priority_cols].isna().sum(),
    "missing_percent": (
        df[priority_cols].isna().mean() * 100
    ).round(2),
    "unique_values": df[priority_cols].nunique()
})

quality_report

                     data_type  missing_count  missing_percent  unique_values
turbine_id               int64              0             0.00          70808
plant_id               float64           5793             8.18           1193
state                      str              0             0.00             46
county                     str              0             0.00            564
project_name               str              0             0.00           1708
project_year           float64            613             0.87             40
turbine_manufacturer       str           5640             7.97             63
turbine_model              str           5777             8.16            315
turbine_capacity_kw    float64           5480             7.74             95
is_retrofitted           int64              0             0.00              2
retrofit_year          float64          64822            91.55              5
longitude              float64              0             0.00          65190
latitude               float64              0             0.00          61962

In [108]:
# Compare the dataset dimensions before and after cleaning
# to document whether any rows or columns were removed
print("BEFORE CLEANING")
print("Rows:", len(df_before_cleaning))
print("Columns:", len(df_before_cleaning.columns))

print("\nAFTER CLEANING")
print("Rows:", len(df))
print("Columns:", len(df.columns))

BEFORE CLEANING
Rows: 70808
Columns: 27

AFTER CLEANING
Rows: 70808
Columns: 27

In [109]:
# Check the current working directory to confirm where files will be
# read from and saved to on this machine
import os

print(os.getcwd())

c:\Users\el3be\Downloads\GA\tab-py-project\data\data

In [110]:
# Save the cleaned dataset to a CSV file using a relative path
# so it saves next to the notebook, no matter where the project folder is moved
df.to_csv(
    "wind_turbine_cleaned_master.csv",
    index=False
)

print("Cleaned file saved!")

Cleaned file saved!

In [111]:
# Reload the cleaned dataset from disk to confirm it was saved correctly
# and to continue working from the cleaned version going forward
import pandas as pd

df = pd.read_csv(
    r"wind_turbine_cleaned_master.csv",
    encoding="latin-1"
)

print(df.shape)

(70808, 27)

In [112]:
# Convert plant_id to a nullable integer type and then to string
# so IDs display without decimal points and missing values are preserved
df["plant_id"] = (
    pd.to_numeric(df["plant_id"], errors="coerce")
      .astype("Int64")
      .astype("string")
)

df["plant_id"].head(20)

0     52161
1     52161
2     52161
3      <NA>
4      <NA>
5      <NA>
6      <NA>
7      <NA>
8      <NA>
9      <NA>
10     <NA>
11     <NA>
12     <NA>
13    58661
14    58661
15    57253
16    57253
17     <NA>
18     <NA>
19     <NA>
Name: plant_id, dtype: string

In [113]:
# Define the final set of columns needed for analysis
analysis_cols = [
    "turbine_id",
    "plant_id",
    "state",
    "county",
    "project_name",
    "project_year",
    "turbine_manufacturer",
    "turbine_model",
    "turbine_capacity_kw",
    "is_retrofitted",
    "retrofit_year",
    "longitude",
    "latitude"
]

# Create a focused analysis dataframe containing only these columns
analysis_df = df[analysis_cols].copy()

# Confirm the shape of the analysis dataframe and preview the first rows
print(analysis_df.shape)
analysis_df.head()

(70808, 13)

,turbine_id,plant_id,state,county,project_name,project_year,turbine_manufacturer,turbine_model,turbine_capacity_kw,is_retrofitted,retrofit_year,longitude,latitude
0,3072661,52161,CA,Kern County,251 Wind,1987.0,Vestas,NaN,95.0,0,NaN,-118.363762,35.077908
1,3072695,52161,CA,Kern County,251 Wind,1987.0,Vestas,NaN,95.0,0,NaN,-118.364410,35.077435
2,3072704,52161,CA,Kern County,251 Wind,1987.0,Vestas,NaN,95.0,0,NaN,-118.364197,35.077644
3,3063272,<NA>,IA,Story County,30 MW Iowa DG Portfolio,2017.0,Nordex,AW125/3000,3000.0,0,NaN,-93.430367,42.028233
4,3053390,<NA>,IA,Boone County,30 MW Iowa DG Portfolio,2017.0,Nordex,AW125/3000,3000.0,0,NaN,-93.700424,41.977608

In [ ]:
# Save the analysis as ready dataframe to a CSV file for use in
# downstream analysis and visualization
analysis_df.to_csv(
    "Wind_Turbine_Cleaned.csv",
    index=False
)

In [ ]:
# Re save the analysis file to ensure the latest version is written to disk
analysis_df.to_csv(
    "Wind_Turbine_Cleaned.csv",
    index=False
)

In [116]:
# Confirm the exact file path and verify that the analysis file
# was successfully saved to disk
import os

print(os.path.abspath("Wind_Turbine_Cleaned.csv"))
print(os.path.exists("Wind_Turbine_Cleaned.csv"))

c:\Users\el3be\Downloads\GA\tab-py-project\data\data\Wind_Turbine_Cleaned.csv
True